config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :new, :create, :edit, :show, :update]
  resource :session, only: [:create, :new, :destroy]
  resources :subs, except: [:destroy] do
    resources :posts, only: [:new]
  end
  resources :posts, except: [:new, :index]
  root 'users#index'
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  validates :title, :sub_id, :author_id, presence: true

  belongs_to :sub

  belongs_to :author,
    foreign_key: :author_id,
    class_name: 'User'
  
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text             not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  validates :title, :description, :moderator_id, presence: true
  validates :title, uniqueness: true

  belongs_to :moderator,
    foreign_key: :moderator_id,
    class_name: 'User'

  has_many :posts

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :username, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 2 }, allow_nil: true

  after_initialize :ensure_session_token

  has_many :moderated_subs,
    foreign_key: :moderator_id,
    class_name: 'Sub'

  has_many :posts,
    foreign_key: :author_id,
    class_name: 'Post'

  attr_reader :password

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    if user
      user.is_password?(password) ? user : nil
    else
      nil
    end
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64(16)
    save!
    session_token
  end

  def is_password?(password)
    check_password = BCrypt::Password.new(password_digest)
    check_password.is_password?(password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def login(user)
    session[:session_token] = user.reset_session_token
  end

  def logout(user)
    user.reset_session_token
    session[:session_token] = nil
  end

  def require_login!
    unless current_user
      flash[:errors] = ["Please log in"]
      redirect_to new_session_url
    end
  end

  def require_admin!
    subb = Sub.find(params[:id])
    mod_id = subb.moderator_id

    unless current_user.id == mod_id
      flash[:errors] =["This isn't your sub! Get out of here!"]
      redirect_to subs_url
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new(sub_id: params[:sub_id])
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id

    if @post.save
      flash[:messages] = ["post created"]
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:messages] = ["Post updated"]
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def destroy
    @post = Post.find(params[:id])
    subb = @post.sub
    if @post
      @post.destroy
      flash[:messages] = ["Its gone!"]
      redirect_to sub_url(subb)
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, :sub_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    unless current_user
      render :new
    else
      redirect_to user_url(current_user)
    end
  end

  def create
    username = params[:user][:username]
    password = params[:user][:password]

    @user = User.find_by_credentials(username, password)

    if @user
      login(@user)
      flash[:message] = ["welcome back #{@user.username}"]
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["invalid credentials"]
      render :new
    end
  end


  def destroy
    logout(current_user)
    redirect_to users_url
  end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_login!, except: [:index, :show]
  before_action :require_admin!, only: [:edit, :update]

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      flash[:messages] = ["New sub created!"]
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      flash[:messages] = ["#{@sub.title} updated"]
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def index
    @subs = Sub.all
    render :index
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_login!, except: [:index, :new, :create]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def index
    if current_user
      redirect_to user_url(current_user)
    else
      render :index
    end
  end

  def edit
    @user = User.find(params[:id])
    render :edit
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:messages] = ["user updated"]
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    token = <<-HTML
      <input type="hidden"
             name="authenticity_token"
             value="#{form_authenticity_token}">
    HTML
    token.html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper

  def is_moderator?
    current_user.id == @sub.moderator_id
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:errors] %>
<ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
</ul>
<% end %>

<% if flash[:messages] %>
<ul>
  <% flash[:messages].each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>
<% end %>

<% if current_user %>
  <%= button_to "log out", session_url, method: "delete" %>
<% end %>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<form action="<%= action %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="<%= method %>">

  <input type="hidden" name="post[sub_id]" value="<%= @post.sub_id%>">

  <label>Post Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>

  <br>

  <label>URL for a Link Post
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>

  <br>

  <label>Post Content
    <input type="textarea" name="post[content]" value="<%= @post.content %>">
  </label>

  <br><br>

  <input type="submit" value="<%= submit_text %>">
</form>

app/views/posts/_post.html.erb
<li>
  <%= link_to post.title, post_url(post) %>
  <%= link_to 'delete', post_url(post), method: :delete %>
</li>

app/views/posts/edit.html.erb
<h1>Edit your kickass post!</h1>
<h2>its friday</h2>

<%= render partial: 'form',
           locals: { method: 'patch',
                     action: posts_url,
                     submit_text: 'yupdate' }%>

app/views/posts/new.html.erb
<h1>Create a kickass post!</h1>
<h2>its friday</h2>

<%= render partial: 'form',
           locals: { method: 'post',
                     action: posts_url,
                     submit_text: 'post' }%>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<h2>by <%= @post.author.username %></h2>
<p>Post created <%= time_ago_in_words(@post.created_at) %> ago</p>

<% unless @post.url == "" %>
<p><%= link_to "Check out the link", @post.url %></p>
<% end %>

<p><%= @post.content %></p>

<% if current_user == @post.author %>
<p><%= link_to "edit", edit_post_url(@post) %></p>
<% end %>


<p><%= link_to "Back to the sub(not)reddit", sub_url(@post.sub) %></p>

app/views/subs/_form.html.erb
<form action="<%= action %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="<%= method %>">
  <label>Sub Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>

  <br>

  <label>Sub Description
    <input type="textarea" name="sub[description]" value="<%= @sub.description %>">
  </label>

  <br><br>

  <input type="submit" value="<%= submit_text %>">
</form>

app/views/subs/_sub.html.erb
<li><%= link_to sub.title, sub_url(sub) %></li>

app/views/subs/edit.html.erb
<h1>Create a new sub</h1>
<%= render partial: 'form',
           locals: { method: 'patch',
                     action: sub_url(@sub),
                     submit_text: 'update' } %>

app/views/subs/index.html.erb
<h1> All of the subs!</h1>

<ul>
  <%= render @subs %>
</ul>

app/views/subs/new.html.erb
<h1>Create a new sub</h1>
<%= render partial: 'form',
           locals: { method: 'post',
                     action: subs_url,
                     submit_text: 'create' } %>

app/views/subs/show.html.erb
<h1> <%= @sub.title %> </h1>

<p> <%= @sub.description %> </p>


  <%= render @sub.posts %>
<br>
<%= link_to "Create a new post in this sub", new_sub_post_url(@sub.id) %>
<br>
<% if current_user && is_moderator? %>
<%= link_to "edit", edit_sub_url(@sub) %>
<br>
<% end %>

<%= link_to "subs", subs_url %>

app/views/users/_form.html.erb
<form action="<%= action %>" method="post">

  <%= auth_token %>

  <input type="hidden" name="_method" value="<%= method %>">
  <label>Username
  <input type="text" name="user[username]" value="<%= @user.username %>">
  </label>
  <br>
  <label>Password
  <input type="password" name="user[password]" value="">
  </label>
  <br><br>
  <input type="submit" value="<%= submit_text %>">

</form>

app/views/users/edit.html.erb
<h1> edit user </h1>
<%= render partial: 'form',
           locals: { method: 'patch',
                     action: user_url(@user),
                     submit_text: 'update' } %>

app/views/users/index.html.erb
<h1>welcome to nathan and noah's reddit</h1>

<h2>please <%= link_to "sign in", new_session_url %> or <%= link_to "sign up", new_user_url %></h2>

app/views/users/new.html.erb
<h1> create a new user </h1>
<%= render partial: 'form',
           locals: { method: 'post',
                     action: users_url,
                     submit_text: 'create' } %>

app/views/users/show.html.erb
<h1> This is <%= @user.username %>'s page</h1>
<%= link_to "edit", edit_user_url(@user) %>
<br>
<%= link_to "check out all of the subs", subs_url %>